const assert=require('node:assert/strict');
const {chromium}=require('playwright');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto('http://localhost:4173');
  await page.locator('.province-label').last().waitFor();
  assert(await page.locator('.province-label').count()>0);
  const countryCoverage=await page.evaluate(()=>document.querySelectorAll('.province-label').length+[...document.querySelectorAll('[data-country-cluster]')].reduce((n,el)=>n+el.dataset.countryCluster.split('|').length,0));
  assert.equal(countryCoverage,34);
  assert.equal(await page.locator('#zoomReset').innerText(),'40%');
  assert.equal(await page.locator('.province-marker.active').count(),0);
  await page.locator('#topSearchInput').fill('Hồ Chí Minh');
  await page.locator('.province-entry[data-province="TP. Hồ Chí Minh"]').click();
  await page.locator('#districtSearch').waitFor();
  assert.equal(await page.locator('.hcm-directory [data-hcm-place]').count(),43);
  assert.equal(await page.locator('.hcm-district-card').count(),22);
  assert(await page.locator('.hcm-directory').evaluate(el=>getComputedStyle(el).overflowY==='auto'&&el.scrollHeight>el.clientHeight));
  assert(await page.locator('.district-cluster').count()>0);
  await page.locator('[data-cluster="Quận 1"]').click();
  assert(await page.locator('.cluster-lines line').count()>1);
  await page.locator('#districtSearch').fill('Dinh');
  await page.locator('.hcm-directory [data-hcm-place="Dinh Độc Lập"]').click();
  assert((await page.locator('#details').innerText()).includes('135 Nam Kỳ'));
  assert.equal(await page.locator('.hcm-place-marker.active').count(),1);
  await page.locator('[data-hcm-clear]').click();
  assert.equal(await page.locator('.hcm-place-marker.active').count(),0);
  await page.locator('#districtSearch').fill('');
  const retained=await page.locator('.hcm-directory').evaluate(el=>{el.scrollTop=200;return el.scrollTop;});
  await page.locator('[data-cluster="Bình Thạnh"]').click();
  assert.equal(await page.locator('.hcm-directory').evaluate(el=>el.scrollTop),retained);
  await page.screenshot({path:'map-desktop-test.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'map-mobile-test.png',fullPage:true});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile horizontal overflow');
  await page.locator('[data-region-view="Tất cả"]').click();
  assert.equal(await page.locator('#zoomReset').innerText(),'40%');
  await page.screenshot({path:'map-country-test.png',fullPage:true});
  assert(await page.locator('.country-cluster').count()>0);
  await page.locator('.country-cluster').first().click();
  await page.locator('[data-province-choice]').first().click();
  assert.equal(await page.locator('.province-preview').count(),1);
  await page.locator('#topSearchInput').fill('Đà Nẵng');
  await page.locator('.province-entry[data-province="Đà Nẵng"]').click();
  await page.screenshot({path:'map-province-test.png',fullPage:true});
  await page.locator('.province-point-choices [data-select="da-nang"]').click();
  assert((await page.locator('#details').textContent()).includes('Điểm đến của bạn'));
  assert.equal(await page.locator('.province-landmark-preview').count(),1);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Province mobile overflow');
  assert.deepEqual(errors,[]);
  await browser.close();console.log('PASS: desktop/mobile selection, clustering, search, reset, province details; no JS errors');
})().catch(error=>{console.error(error);process.exit(1)});
